server:
  port: 3000
application:
  domain: bekk.no
  name: 'Bekk CTF'
  logo: 'https://github.com/bekk/juice-shop/raw/master/frontend/src/assets/public/images/bekklogo.png'
  favicon: 'https://www.bekk.no/favicon.ico'
  numberOfRandomFakeUsers: 0
  showChallengeSolvedNotifications: true
  showChallengeHints: false
  theme: bluegrey-lightgreen
  gitHubRibbon: false
  showVersionNumber: false
  twitterUrl: 'https://twitter.com/owasp_juiceshop'
  facebookUrl: null
  slackUrl: null
  pressKitUrl: null
  planetOverlayMap: orangemap2k.jpg
  planetName: Orangeuze
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  altcoinName: BekkCoin
  cookieConsent:
    backgroundColor: '#6D7ABB'
    textColor: '#ffffff'
    buttonColor: '#A1F5E3'
    buttonTextColor: '#ffffff'
    message: 'Denne nettsiden benytter en mengde med 3. parts informasjonskapsler for din beleilighet og sporbarhet.'
    dismissText: 'Sure, whatever!'
    linkText: 'Hvordan kan jeg skru av dette?'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@bekk.no'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
  promotion:
    video: JuiceShopJingle.mp4
    subtitles: JuiceShopJingle.vtt
challenges:
  safetyOverride: false
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
products:
  -
    name: 'Bekk Juice'
    description: 'Laget med vann fra naturlige data streams.'
    price: 19.00
    image: banana_juice.jpg
  -
    name: 'Antikke Bekk Band Billetter'
    description: 'Fra Oslo-Tour 2002'
    price: 249.00
    image: 'http://icons.iconarchive.com/icons/webalys/kameleon.pics/512/Rocker-icon.png'
    reviews:
      - { text: 'Bekk Band for life ♥', author: Jøran }
  -
    name: 'Kaffekapsler (600 stk)'
    description: '2 dagers forbruk'
    price: 2750.00
    image: 'http://icons.iconarchive.com/icons/tatice/cristal-intense/128/Java-icon.png'
  -
    name: 'Eple Juice (1000ml)'
    price: 1.99
    description: 'The all-time classic.'
    image: apple_juice.jpg
    reviews: # Options 'author': admin, jim, bender, ciso, support, morty, mc.safesearch
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'Appelsin Juice (1000ml)'
    description: 'Laget av appelsiner håndplukket av onkel Dittmeyer.'
    price: 2.99
    image: orange_juice.jpg
  -
    name: 'Eggfrukt Juice (500ml)'
    description: 'Nå med enda mer eksotisk smak.'
    price: 8.99
    image: eggfruit_juice.jpg
    reviews:
      - { text: 'Jeg kjøpte den, hadde kjøpt igjen. 5/7', author: admin }
  -
    name: 'Bringebær Juice (1000ml)'
    description: 'Laget av et par Raspberry Pi i blendern, vann og sukker.'
    price: 4.99
    image: raspberry_juice.jpg
  -
    name: 'Sitron Juice (500ml)'
    description: 'Sur, men full av vitaminer.'
    price: 2.99
    image: lemon_juice.jpg
  -
    name: 'Banan Juice (1000ml)'
    description: 'Aper elsker det mest :D'
    price: 1.99
    image: banana_juice.jpg
    reviews:
      - { text: 'Fry likte det også.', author: bender }
  -
    name: 'OWASP Juice Shop T-Shirt'
    description: 'Ekte fans bruker den 24/7!'
    price: 22.49
    image: fan_shirt.jpg
  -
    name: 'OWASP Juice Shop CTF Jente-Shirt'
    description: 'Kun for seriøse Capture-the-Flag-Heroinner!'
    price: 22.49
    image: fan_girlie.jpg
  -
    name: '10 pack med Bekk-tatovering (O-Saft)'
    description: 'Se ut som en Bekker for resten av livet'
    price: 0.01
    image: orange_juice.jpg
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
  -
    name: 'Julens superoveraskelsesboks (2014 Edition)'
    description: 'Inneholder et random utvalg av klistremerker og tre unisex t-shirts, til en uslåelig pris!'
    price: 29.99
    image: undefined.jpg
    useForChristmasSpecialChallenge: true
  -
    name: 'Rippertuer Spesial Juice'
    description: 'Inneholder en magisk samling av de mest skjeldene frukter samlet fra rundt i verden, som Cherymoya Annona cherimola, Jabuticaba Myrciaria cauliflora, Bael Aegle marmelos... og andre, til en uslåelig pris! <br/><span style="color:red;">Dette produktet er ikke lengre tilgjengelig grunnet mathelse og sikkerhet.</span>'
    price: 16.99
    image: undefined.jpg
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'OWASP Juice Shop Sticker (2015/2016 design)'
    description: 'Laserkuttet stickers med offisiell 2015/2016 logo. Er nå blitt skjelden samlevare. <em>Tomt på lager!</em>'
    price: 999.99
    image: sticker.png
    deletedDate: '2017-04-28'
  -
    name: 'OWASP Juice Shop Iron-Ons (16pcs)'
    description: 'Oppgrader klærne dine med vaskemaskintrygge <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">iron-ons</a> med OWASP Juice Shop eller CTF Extension logo!'
    price: 14.99
    image: iron-on.jpg
  -
    name: 'OWASP Juice Shop Magneter (16pcs)'
    description: 'Kjøleskapet ditt blir kulere med disse OWASP Juice Shop eller CTF Extension logo<a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">magnetene</a>!'
    price: 15.99
    image: magnets.jpg
  -
    name: 'OWASP Juice Shop Sticker Side'
    description: 'Uendelig dekorasjonsmuligheter med disse OWASP Juice Shop eller CTF Extension <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">klistremerkesidene</a>! Hver side har 16 stickers.'
    price: 9.99
    image: sticker_page.jpg
  -
    name: 'OWASP Juice Shop Sticker Single'
    description: 'Superhøy kvalitetsvinyl <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">sticker single</a> med OWASP Juice Shop eller CTF Extension logo! Den ultimate laptop stickern!'
    price: 4.99
    image: sticker_single.jpg
  -
    name: 'OWASP Juice Shop Midlertidig Tattoos (16pcs)'
    description: 'Få deg en av disse <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">midlertidige tattooveringene</a>. Så du stolt og midlertidig kan bære OWASP Juice Shop eller CTF Extension logo på huden. Hvis du tweeter bilde av deg med tatovering, husk å tagge <a href="https://twitter.com/owasp_juiceshop" target="_blank"><code>@owasp_juiceshop</code></a>!'
    price: 14.99
    image: tattoo.jpg
    reviews:
      - { text: 'I straight-up gots nuff props fo''these tattoos!', author: mc.safesearch }
  -
    name: 'OWASP Juice Shop Kaffekopp'
    description: 'Svart kopp med vanlig logo på en side, og CTF logo på andre siden. Dine kolleger vil bli grønn av misunnelse!'
    price: 21.99
    image: fan_mug.jpg
  -
    name: 'OWASP Juice Shop Hoodie'
    description: 'Mr. Robot-style genser. Kommer i svart, og med logo.'
    price: 49.99
    image: fan_hoodie.jpg
  -
    name: 'OWASP Juice Shop-CTF Borrelås Patch'
    description: '4x3.5" brodert patch med borrelås bakside. Det ultimate decal for hver taktisk sekk eller bag!'
    price: 2.92
    image: velcro-patch.jpg
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: mc.safesearch }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'Woodruff Sirup "Forest Master X-Treme"'
    description: 'Høstet og produsert i Black Forest, Tyskland. Kan forårsake hyperaktiv oppførsel hos barn. Kan forårsake permanent grønn tunge hvis inntatt ublandet.'
    price: 6.99
    image: woodruff_syrup.jpg
  -
    name: 'Grønn Smoothie'
    description: 'Ser giftig ut, men er faktisk veldig sunt for deg, og kroppen din. Laget av kål, spinat, kiwi og gress fra en park på Grünerløkka.'
    price: 1.99
    image: green_smoothie.jpg
    reviews:
      - { text: 'Fresh out of a replicator.', author: jim }
  -
    name: 'Quince Juice (1000ml)'
    description: 'Juice fra <em>Cydonia oblonga</em> frukten. Ikke akkurat søt, men veldig rik på Vitamin C.'
    price: 4.99
    image: quince.jpg
  -
    name: 'Eple Pomace'
    description: 'Fineste pressingen av epler fra Sogn&Fjordane. Alergi: Kan inneholde spor av mark. Kan <a href="/#recycle">sendes tilbake til oss for</a> resirkulering.'
    price: 0.89
    image: apple_pressings.jpg
  -
    name: 'Fruktpresse'
    description: 'Frukt går inn, juice kommer ut. Pomace kan du sende tilbake til oss for resirkulering.'
    price: 89.99
    image: fruit_press.jpg
  -
    name: 'OWASP Juice Shop Logo (3D-printed)'
    description: 'Denne dingsen er uhyre skjelden, og ble håndlaget i Sverige. Dette er grunnen til at den er sykt dyr, til tross for sin manglende funksjon i livet..'
    price: 99.99
    image: 3d_keychain.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
  -
    name: 'Juice Shop Kunst'
    description: 'Unikt mesterverk malt med forskjellig typer juice on 90g/m² lined papir.'
    price: 278.74
    image: artwork.jpg
  -
    name: 'Global OWASP WASPY Award 2017 Nomnation'
    description: 'Din mulighet til å nominere opp til tre stille pilaterer i OWASP samfunnet ender den 30.06.2017! <a href="https://www.owasp.org/index.php/WASPY_Awards_2017">Nominer nå!!</a>'
    price: 0.03
    image: waspy.png
    deletedDate: '2017-07-01'
  -
    name: 'Jorbærsaft (500ml)'
    description: 'Søt & smakfull!'
    price: 3.99
    image: strawberry_juice.jpeg
  -
    name: 'Gulrot Juice (1000ml)'
    description: 'Som det gamle tyske utsagnet sier: "Gulrot er bra for synet. Eller har noen sett en kanin med briller?"'
    price: 2.99
    image: carrot_juice.jpeg
  -
    name: 'OWASP Juice Shop Sverige Tour 2017 Sticker Ark (Special Edition)'
    description: '10 ark av svensk-themed stickers med 15 stickers på hver.'
    price: 19.1
    image: stickersheet_se.png
    deletedDate: '2017-09-20'
  -
    name: 'Pwning OWASP Juice Shop'
    description: '<em>Den ofesielle Companion Guide</em> av Björn Kimminich tilgjengelig <a href="https://leanpub.com/juice-shop">gratis</a> og <a href="https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/">lesbar på GitBook</a>!'
    price: 5.99
    image: cover_small.jpg
    reviews:
      - { text: 'Even more interesting than watching Interdimensional Cable!', author: morty }
  -
    name: 'Melon Sykkel (Comeback-Product 2018 Edition)'
    description: 'Hjulene på denne syklen er laget av ekte vannmelon. Du vil kanskje ikke hoppe opp og ned fortauskanter for hardt med denne.'
    price: 2999
    image: melon_bike.jpeg
  -
    name: 'OWASP Juice Shop Coaster (10pcs)'
    description: 'Våre 95mm sirkulære drikkebrikker er printet i fullfarge og laget fra tykke premium drikkebrikkeplanker.'
    price: 19.99
    image: coaster.png
ctf:
  showFlagsInNotifications: true
